name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        php-version: [8.1]

    steps:
    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: pcov

    - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        files: ./coverage.xml

    - uses: paambaati/codeclimate-action@v4
      continue-on-error: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: ''
        coverageLocations: ./coverage.xml:clover
