name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        php-version: [8.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: pcov

    - name: Install PHP dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      continue-on-error: true
      with:
        files: ./coverage.xml

    - name: Upload coverage to codeclimate
      uses: paambaati/codeclimate-action@v3.0.0
      continue-on-error: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: ''
        coverageLocations: ./coverage.xml:clover
